### ISSUE TITLE
Swing code uses javafx classes?

### ISSUE THREAD

**Issue by hrj** [IDRSolutions/maven-OpenViewerFX-src#1]
From a quick look, the [swing viewer](https://github.com/IDRSolutions/maven-OpenViewerFX-src/blob/master/OpenViewerFX/src/main/java/org/jpedal/render/SwingDisplay.java) seems to use JavaFx classes such as `javafx.geometry.Bounds`. This is fine with Oracle JRE 8, but it won't work with other JREs since JavaFX is not part of Java SE yet. Is this something you are planning to address?

-------

BTW, Hi!

Thanks for opening this repo. Coincidentally, I was just now trying to integrate this library with [gngr](https://github.com/uprootlabs/gngr) and looking at our emails and your website when I found this newly created repo!

**Comment by IDRSolutions** [comment]
There is no swing viewer. There is a leagcy SwingDisplay class which is used for some features (ie T3 font handling) and will diasappear in later releases

**Comment by hrj** [comment]
Oh ok, thanks for the clarification.
