### ISSUE TITLE
incompatibility with bouncycastle 1.51

### ISSUE THREAD

**Issue by jgmbenoit** [IDRSolutions/maven-OpenViewerFX-src#4]
OpenViewerFX fails to build from source due to an incompatibility with bouncycastle 1.51 (current version for Debian testing):

OpenViewerFX/src/main/java/org/jpedal/io/CertificateReader.java:69: error: method getContent in class RecipientInformation cannot be applied to given types;
                        envelopedData = recipientInfo.getContent(key, provider);
                                                     ^
  required: Recipient
  found: Key,String
  reason: actual and formal argument lists differ in length

**Comment by IDRSolutions** [comment]
There are no plans to change it at present
