### ISSUE TITLE
Please list links to dependencies

### ISSUE THREAD

**Issue by paxromana96** [IDRSolutions/maven-OpenViewerFX-src#5]
I'm trying to use OpenViewerFX for an academic project, and I'm still struggling to compile. I had to hunt through the source code to find what packages to download, and in some cases that still wasn't sufficient (see other issue about Bouncy Castle 1.5).

It would be helpful to new users to include links to dependencies' websites, or to a working .jar of the project. Otherwise we're just going to find another implementation to use.

**Comment by IDRSolutions** [comment]
> On 16 Mar 2016, at 16:05, Jack Brown <notifications@github.com> wrote:
> 
> I'm trying to use OpenViewerFX for an academic project, and I'm still struggling to compile. I had to hunt through the source code to find what packages to download, and in some cases that still wasn't sufficient (see other issue about Bouncy Castle 1.5).
> 
> It would be helpful to new users to include links to dependencies' websites, or to a working .jar of the project. Otherwise we're just going to find another implementation to use.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub <https://github.com/IDRSolutions/maven-OpenViewerFX-src/issues/5>
I would recommend running the jar which is on github rather than compiling from source.

Regards,

MArk
